spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springvault
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379